[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AutoGrad = "6710c13c-97f1-543f-91c5-74e8f7d95b35"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Knet = "1902f260-5fb4-5aff-8c31-6271790ab950"
MarkovModels = "c2ae6250-d0a1-11ea-0991-234599ce5244"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpeechFeatures = "6f3487c4-5ca2-4050-bfeb-2cf56df92307"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
